name: Build Development APK

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build apk --flavor development --target lib/main_development.dart
      - uses: actions/upload-artifact@v4
        with:
          name: abs-wear-development-apk
          path: build/app/outputs/flutter-apk/app-development.apk
